name: homepage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6  # Versión de `http`
  crypto: ^3.0.0
  firebase_core: ^3.7.0  # Dependencia de firebase_core
  firebase_auth: ^5.3.2  # Dependencia de firebase_auth
  cloud_firestore: ^5.0.0  # Dependencia de Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpeg  # Asegúrate de que esta imagen esté en la carpeta assets
    - assets/logotipo.png         # Si tienes un logo, también lo puedes agregar aquí
